# Permalinks
permalink:           pretty

# Setup
title:               Dallas Nite Theme
tagline:             Did you ever see Dallas from a DC-9 at nite?
url:                 https://corbtastik.github.io/dallas-nite/
paginate:            1
baseurl:             ""

exclude: [docs]
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              corbs
  url:               https://github.com/corbtastik
  
# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/corbtastik/dallas-nite

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - github-pages
